AkeneoUnitToSuffix = {
    'KILOGRAM': 'kg',
    'GRAM': 'g',
    'MILLIGRAM': 'mg',
    'MICROGRAM': 'µg',
    'TON': 't',
    'POUND': 'lb',
    'OUNCE': 'oz',
    'MILLIMETER': 'mm',
    'CENTIMETER': 'cm',
    'METER': 'm',
    'KILOMETER': 'km',
    'INCH': 'in',
    'FOOT': 'ft',
    'YARD': 'yd',
    'PIECE': 'pc',
    'DOZEN': 'dz',
    'MILLILITER': 'ml',
    'CENTILITER': 'cl',
    'LITER': 'l',
    'GALLON': 'gal',
    'BOX': 'box',
    'PACK': 'pack',
    'BOTTLE': 'bottle',
}